### ISSUE TITLE
Console Logging

### ISSUE THREAD

**Issue by j0hnnyblaz3** [gadfly361/re-pollsive#3]
Hello,

Thank you for this very useful library. I have a quick question. Is there a way to turn off logging to console? Sometimes it's helpful but other times it is a lot of noise. 

Thanks!

**Comment by gadfly361** [comment]
@j0hnnyblaz3 I don't believe there is any logging. 

When you started a polling event, did you happen to add a print statement? 

If that isn't the case though, can you add the logs here so I can take a peak and see what could potentially be causing it

**Comment by j0hnnyblaz3** [comment]
Thanks for the quick response. I looked a little closer and realized it was kee-frame doing the logging. 
The polling was calling an API endpoint and was going through a kee-frame chain. 

Sorry to have bothered you.

**Comment by gadfly361** [comment]
@j0hnnyblaz3 no bother at all! Glad you figured it out though :)
